version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: pruebabackenddb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yournewsecurepassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: ./PruebaBackend.Api
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Host=db;Port=5432;Database=pruebabackenddb;Username=postgres;Password=yournewsecurepassword
    ports:
      - "5000:80"
    depends_on:
      - db

volumes:
  postgres_data: